Vehicle = {}

-- [[ Vehicle Settings ]] --
Vehicle.VehicleSettings = {
    -- [[ San Andreas Highway Patrol || SAHP ]] --
    ["sp14charger"] = {
        ["extras"] = {
            ["1"] = false, -- on/off
            ["2"] = false,
            ["3"] = false,
            ["4"] = false,
            ["5"] = false,
            ["6"] = false,
            ["7"] = false,
            ["8"] = false,
            ["9"] = false,
            ["10"] = false,
            ["11"] = false,
            ["12"] = false,
            ["13"] = false,
        },
		["livery"] = 0,
    },
    ["sp18charger"] = {
        ["extras"] = {
            ["1"] = false, -- on/off
            ["2"] = false,
            ["3"] = false,
            ["4"] = false,
            ["5"] = false,
            ["6"] = false,
            ["7"] = false,
            ["8"] = false,
            ["9"] = false,
            ["10"] = false,
            ["11"] = false,
            ["12"] = false,
            ["13"] = false,
        },
		["livery"] = 0,
    },
    ["fastback"] = {
        ["extras"] = {
            ["1"] = false, -- on/off
            ["2"] = false,
            ["3"] = false,
            ["4"] = false,
            ["5"] = false,
            ["6"] = false,
            ["7"] = false,
            ["8"] = false,
            ["9"] = false,
            ["10"] = false,
            ["11"] = false,
            ["12"] = false,
            ["13"] = false,
        },
		["livery"] = 0,
    },

    -- [[ Los Santos Police Department || LSPD ]] --
    ["valor1bb"] = { --- Model name
        ["extras"] = {
            ["1"] = true, -- on/off
            ["2"] = false,
            ["3"] = true,
            ["4"] = true,
            ["5"] = true,
            ["6"] = true,
            ["7"] = true,
            ["8"] = true,
            ["9"] = true,
            ["10"] = true,
            ["11"] = true,
            ["12"] = true,
            ["13"] = true,
        },
		["livery"] = 0,
    },
    ["valor5bb"] = { --- Model name
        ["extras"] = {
            ["1"] = true, -- on/off
            ["2"] = false,
            ["3"] = true,
            ["4"] = true,
            ["5"] = true,
            ["6"] = true,
            ["7"] = true,
            ["8"] = true,
            ["9"] = true,
            ["10"] = true,
            ["11"] = true,
            ["12"] = true,
            ["13"] = true,
        },
		["livery"] = 0,
    },
    ["valor4bb"] = { --- Model name
        ["extras"] = {
            ["1"] = true, -- on/off
            ["2"] = false,
            ["3"] = true,
            ["4"] = true,
            ["5"] = true,
            ["6"] = true,
            ["7"] = true,
            ["8"] = true,
            ["9"] = true,
            ["10"] = true,
            ["11"] = true,
            ["12"] = true,
            ["13"] = true,
        },
		["livery"] = 0,
    },
    ["valor11bb"] = { --- Model name
        ["extras"] = {
            ["1"] = true, -- on/off
            ["2"] = false,
            ["3"] = true,
            ["4"] = true,
            ["5"] = true,
            ["6"] = true,
            ["7"] = true,
            ["8"] = true,
            ["9"] = true,
            ["10"] = true,
            ["11"] = true,
            ["12"] = true,
            ["13"] = true,
        },
		["livery"] = 0,
    },
    ["valor2bb"] = { --- Model name
        ["extras"] = {
            ["1"] = true, -- on/off
            ["2"] = false,
            ["3"] = true,
            ["4"] = true,
            ["5"] = true,
            ["6"] = true,
            ["7"] = true,
            ["8"] = true,
            ["9"] = true,
            ["10"] = true,
            ["11"] = true,
            ["12"] = true,
            ["13"] = true,
        },
		["livery"] = 0,
    },
    ["valor7bb"] = { --- Model name
        ["extras"] = {
            ["1"] = true, -- on/off
            ["2"] = false,
            ["3"] = true,
            ["4"] = true,
            ["5"] = true,
            ["6"] = true,
            ["7"] = true,
            ["8"] = true,
            ["9"] = true,
            ["10"] = true,
            ["11"] = true,
            ["12"] = true,
            ["13"] = true,
        },
		["livery"] = 0,
    },
    ["valor12bb"] = { --- Model name
        ["extras"] = {
            ["1"] = true, -- on/off
            ["2"] = false,
            ["3"] = true,
            ["4"] = true,
            ["5"] = true,
            ["6"] = true,
            ["7"] = true,
            ["8"] = true,
            ["9"] = true,
            ["10"] = true,
            ["11"] = true,
            ["12"] = true,
            ["13"] = true,
        },
		["livery"] = 0,
    },
    ["valor14bb"] = { --- Model name
        ["extras"] = {
            ["1"] = true, -- on/off
            ["2"] = false,
            ["3"] = true,
            ["4"] = true,
            ["5"] = true,
            ["6"] = true,
            ["7"] = true,
            ["8"] = true,
            ["9"] = true,
            ["10"] = true,
            ["11"] = true,
            ["12"] = true,
            ["13"] = true,
        },
		["livery"] = 0,
    },
    ["valor6bb"] = { --- Model name
        ["extras"] = {
            ["1"] = true, -- on/off
            ["2"] = false,
            ["3"] = true,
            ["4"] = true,
            ["5"] = true,
            ["6"] = true,
            ["7"] = true,
            ["8"] = true,
            ["9"] = true,
            ["10"] = true,
            ["11"] = true,
            ["12"] = true,
            ["13"] = true,
        },
		["livery"] = 0,
    },
    ["valor13bb"] = { --- Model name
        ["extras"] = {
            ["1"] = true, -- on/off
            ["2"] = false,
            ["3"] = true,
            ["4"] = true,
            ["5"] = true,
            ["6"] = true,
            ["7"] = true,
            ["8"] = true,
            ["9"] = true,
            ["10"] = true,
            ["11"] = true,
            ["12"] = true,
            ["13"] = true,
        },
		["livery"] = 0,
    },
    ["valor8bb"] = { --- Model name
        ["extras"] = {
            ["1"] = true, -- on/off
            ["2"] = false,
            ["3"] = true,
            ["4"] = true,
            ["5"] = true,
            ["6"] = true,
            ["7"] = true,
            ["8"] = true,
            ["9"] = true,
            ["10"] = true,
            ["11"] = true,
            ["12"] = true,
            ["13"] = true,
        },
		["livery"] = 0,
    },
    ["valor10bb"] = { --- Model name
        ["extras"] = {
            ["1"] = true, -- on/off
            ["2"] = false,
            ["3"] = true,
            ["4"] = true,
            ["5"] = true,
            ["6"] = true,
            ["7"] = true,
            ["8"] = true,
            ["9"] = true,
            ["10"] = true,
            ["11"] = true,
            ["12"] = true,
            ["13"] = true,
        },
		["livery"] = 0,
    },
    ["valor9bb"] = { --- Model name
        ["extras"] = {
            ["1"] = true, -- on/off
            ["2"] = false,
            ["3"] = true,
            ["4"] = true,
            ["5"] = true,
            ["6"] = true,
            ["7"] = true,
            ["8"] = true,
            ["9"] = true,
            ["10"] = true,
            ["11"] = true,
            ["12"] = true,
            ["13"] = true,
        },
		["livery"] = 0,
    },

    -- [[ Blaine County Sheriff's Office ]] --
    ["sh1"] = { --- Model name
        ["extras"] = {
            ["1"] = true, -- on/off
            ["2"] = false,
            ["3"] = false,
            ["4"] = true,
            ["5"] = true,
            ["6"] = true,
            ["7"] = true,
            ["8"] = true,
            ["9"] = true,
            ["10"] = true,
            ["11"] = true,
            ["12"] = true,
            ["13"] = true,
        },
        ["livery"] = 0,
    },

    -- [[ San Andreas Fire Department ]] --
    ["fdnyambo"] = { --- Model name
        ["extras"] = {
            ["1"] = true, -- on/off
            ["2"] = true,
            ["3"] = true,
            ["4"] = true,
            ["5"] = true,
            ["6"] = true,
            ["7"] = true,
            ["8"] = true,
            ["9"] = true,
            ["10"] = true,
            ["11"] = true,
            ["12"] = true,
            ["13"] = true,
        },
        ["livery"] = 0,
    },

    -- [[ Federal Vehicles ]] --
    ["cadillacrb"] = { --- Model name
        ["extras"] = {
            ["1"] = true, -- on/off
            ["2"] = true,
            ["3"] = true,
            ["4"] = true,
            ["5"] = true,
            ["6"] = true,
            ["7"] = true,
            ["8"] = true,
            ["9"] = true,
            ["10"] = true,
            ["11"] = true,
            ["12"] = true,
            ["13"] = true,
        },
        ["livery"] = 0,
    },
    ["chevyssrb"] = { --- Model name
        ["extras"] = {
            ["1"] = true, -- on/off
            ["2"] = true,
            ["3"] = true,
            ["4"] = true,
            ["5"] = true,
            ["6"] = true,
            ["7"] = true,
            ["8"] = true,
            ["9"] = true,
            ["10"] = true,
            ["11"] = true,
            ["12"] = true,
            ["13"] = true,
        },
        ["livery"] = 0,
    },
    ["expeditionrb"] = { --- Model name
        ["extras"] = {
            ["1"] = true, -- on/off
            ["2"] = true,
            ["3"] = true,
            ["4"] = true,
            ["5"] = true,
            ["6"] = true,
            ["7"] = true,
            ["8"] = true,
            ["9"] = true,
            ["10"] = true,
            ["11"] = true,
            ["12"] = true,
            ["13"] = true,
        },
        ["livery"] = 0,
    },
    ["f150rb"] = { --- Model name
        ["extras"] = {
            ["1"] = true, -- on/off
            ["2"] = true,
            ["3"] = true,
            ["4"] = true,
            ["5"] = true,
            ["6"] = true,
            ["7"] = true,
            ["8"] = true,
            ["9"] = true,
            ["10"] = true,
            ["11"] = true,
            ["12"] = true,
            ["13"] = true,
        },
        ["livery"] = 0,
    },
    ["taurusrb"] = { --- Model name
        ["extras"] = {
            ["1"] = true, -- on/off
            ["2"] = true,
            ["3"] = true,
            ["4"] = true,
            ["5"] = true,
            ["6"] = true,
            ["7"] = true,
            ["8"] = true,
            ["9"] = true,
            ["10"] = true,
            ["11"] = true,
            ["12"] = true,
            ["13"] = true,
        },
        ["livery"] = 0,
    },
}